-- ALL WORKS IN 1 BIG COPY/PASTE

CREATE TYPE SESSION_TYPES AS ENUM ('Lecture', '1-to-1', 'Practical');
CREATE TYPE TITLE_TYPES AS ENUM ('Mr', 'Mrs', 'Miss', 'Ms', 'Mx', 'Dr', 'Lord', 'Lady');
CREATE TYPE ROOM_TYPES AS ENUM ('Computer Lab', 'Science Lab', 'Classroom', 'Lecture Hall');
CREATE TYPE ENROLMENT_STATUS_TYPE AS ENUM ('Enrolling', 'Complete', 'Dropped Out');

CREATE OR REPLACE FUNCTION PHONE_CODE_REGEX()
RETURNS TEXT AS 
$$
DECLARE REGEX TEXT;
    BEGIN
        REGEX := '\+[0-9]{1,3}';
    RETURN REGEX;
END;
$$
LANGUAGE plpgsql;

-- All valid
CREATE TABLE DEPARTMENT (
    DEPT_ID SERIAL PRIMARY KEY,
    DEPT_NAME VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION TEXT NOT NULL
);


-- All valid
CREATE TABLE COURSE (
    COURSE_ID SERIAL PRIMARY KEY,
    DEPT_ID INT NOT NULL,
    COURSE_NAME VARCHAR(50) UNIQUE NOT NULL,
    COURSE_DESCRIPTION TEXT NOT NULL,
    COURSE_COST DECIMAL(7, 2) NOT NULL,

    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),

    CHECK (COURSE_COST >= 0)
);

-- All valid
CREATE TABLE SUBJECT (
    SUBJECT_ID SERIAL PRIMARY KEY,
    SUBJECT_NAME VARCHAR(50) NOT NULL,
    SUBJECT_LEVEL SMALLINT NOT NULL,
    SUBJECT_DESCRIPTION TEXT NOT NULL,

    CHECK (SUBJECT_LEVEL BETWEEN 4 AND 7),

    UNIQUE(SUBJECT_NAME, SUBJECT_LEVEL)
);

-- All valid
CREATE TABLE COURSE_SUBJECT (
    COURSE_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID),
    
    PRIMARY KEY (COURSE_ID, SUBJECT_ID)
);

-- All valid
CREATE TABLE BRANCH (
    BRANCH_ID SERIAL PRIMARY KEY,
    BRANCH_NAME VARCHAR(30) UNIQUE NOT NULL,
    BRANCH_ADDR1 VARCHAR(50) NOT NULL,
    BRANCH_ADDR2 VARCHAR(50),
    BRANCH_CITY VARCHAR(30) NOT NULL,
    BRANCH_POSTCODE VARCHAR(20),
    BRANCH_COUNTRY_CODE CHAR(2) NOT NULL,
    BRANCH_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    BRANCH_PHONE_COUNTRY_CODE VARCHAR(4),
    BRANCH_PHONE_NUMBER VARCHAR(15) UNIQUE NOT NULL,

    CHECK (BRANCH_PHONE_COUNTRY_CODE SIMILAR TO PHONE_CODE_REGEX())
);

-- All valid
CREATE TABLE STAFF (
    STAFF_ID SERIAL PRIMARY KEY,
    DEPT_ID INT NOT NULL,
    BRANCH_ID INT NOT NULL,
    IS_BRANCH_MANAGER BOOLEAN NOT NULL,
    STAFF_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    STAFF_MOBILE_CODE VARCHAR(4) NOT NULL,
    STAFF_MOBILE_NUMBER VARCHAR(15) UNIQUE NOT NULL,
    STAFF_FIRST_NAME VARCHAR(30) NOT NULL,
    STAFF_MIDDLE_NAME VARCHAR(30),
    STAFF_LAST_NAME VARCHAR(30) NOT NULL,
    STAFF_TITLE TITLE_TYPES NOT NULL,
    STAFF_ADDR1 VARCHAR(50) NOT NULL,
    STAFF_ADDR2 VARCHAR(50),
    STAFF_CITY VARCHAR(30) NOT NULL,
    STAFF_POSTCODE VARCHAR(20),
    STAFF_COUNTRY_CODE CHAR(2) NOT NULL,

    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),

    CHECK (STAFF_MOBILE_CODE SIMILAR TO PHONE_CODE_REGEX())
);

-- All valid
CREATE TABLE STAFF_ASSIGNMENT (
    STAFF_ASSIGNMENT_ID SERIAL PRIMARY KEY,
    BRANCH_MANAGER_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    ASSIGNMENT_TITLE VARCHAR(30) NOT NULL,
    ASSIGNMENT_DESCRIPTION TEXT NOT NULL,
    ASSIGNMENT_DEADLINE TIMESTAMP,
    ASSIGNMENT_COMPLETE BOOLEAN NOT NULL,
    IS_URGENT BOOLEAN NOT NULL,

    FOREIGN KEY (BRANCH_MANAGER_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

-- All valid
CREATE TABLE COURSE_STAFF (
    COURSE_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    
    PRIMARY KEY (COURSE_ID, STAFF_ID)
);

-- All valid
CREATE TABLE ROLE (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROLE_DESCRIPTION TEXT NOT NULL
);

-- All valid
CREATE TABLE STAFF_ROLE (
    STAFF_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,

    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID),

    PRIMARY KEY (STAFF_ID, ROLE_ID)
);

-- All valid
CREATE TABLE STAFF_AVAILABILITY (
    STAFF_ID INT NOT NULL,
    DAY_OF_WEEK SMALLINT NOT NULL,

    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),

    CHECK (DAY_OF_WEEK BETWEEN 1 AND 7),

    PRIMARY KEY (STAFF_ID, DAY_OF_WEEK)
);

-- All valid
CREATE TABLE STAFF_ABSENCE (
    STAFF_ID INT NOT NULL,
    ABSENCE_START TIMESTAMP NOT NULL,
    ABSENCE_END TIMESTAMP NOT NULL,

    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),

    PRIMARY KEY (STAFF_ID, ABSENCE_START, ABSENCE_END)
);

-- All valid
CREATE TABLE ROOM (
    ROOM_ID SERIAL PRIMARY KEY,
    BRANCH_ID INT NOT NULL,
    ROOM_NAME VARCHAR(20) NOT NULL,
    ROOM_TYPE ROOM_TYPES NOT NULL,
    CAPACITY INT NOT NULL,

    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),

    CHECK (CAPACITY > 0)
);

-- All valid
CREATE TABLE FACILITY (
    FACILITY_ID SERIAL PRIMARY KEY,
    FACILITY_NAME VARCHAR(50) UNIQUE NOT NULL
);

-- All valid
CREATE TABLE ROOM_FACILITY (
    ROOM_ID INT NOT NULL,
    FACILITY_ID INT NOT NULL,
    QUANTITY INT NOT NULL,

    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    FOREIGN KEY (FACILITY_ID) REFERENCES FACILITY(FACILITY_ID),

    CHECK (QUANTITY > 0),

    PRIMARY KEY (ROOM_ID, FACILITY_ID)
);

-- All valid
CREATE TABLE STUDENT(
    STUDENT_ID SERIAL PRIMARY KEY,
    STUDENT_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    STUDENT_FIRST_NAME VARCHAR(30) NOT NULL,
    STUDENT_MIDDLE_NAME VARCHAR(30),
    STUDENT_LAST_NAME VARCHAR(30) NOT NULL,
    STUDENT_TITLE TITLE_TYPES NOT NULL,
    STUDENT_MOBILE_CODE VARCHAR(4) NOT NULL,
    STUDENT_MOBILE VARCHAR(15) UNIQUE NOT NULL,
    STUDENT_ADDR1 VARCHAR(50) NOT NULL,
    STUDENT_ADDR2 VARCHAR(50),
    STUDENT_CITY VARCHAR(30) NOT NULL,
    STUDENT_POSTCODE VARCHAR(20),
    STUDENT_COUNTRY_CODE CHAR(2) NOT NULL,
    STUDENT_DATE_OF_BIRTH DATE NOT NULL,

    CHECK (STUDENT_MOBILE_CODE SIMILAR TO PHONE_CODE_REGEX())
);

-- All valid
CREATE TABLE EMERGENCY_CONTACT (
    STUDENT_EMERGENCY_CONTACT_ID SERIAL PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    STUDENT_EMERGENCY_CONTACT_FIRST_NAME VARCHAR(30) NOT NULL,
    STUDENT_EMERGENCY_CONTACT_LAST_NAME VARCHAR(30) NOT NULL,
    STUDENT_EMERGENCY_CONTACT_RELATIONSHIP VARCHAR(20) NOT NULL,
    STUDENT_EMERGENCY_PHONE_COUNTRY_CODE VARCHAR(4) NOT NULL,
    STUDENT_EMERGENCY_CONTACT_NUMBER VARCHAR(15) UNIQUE NOT NULL,
    STUDENT_EMERGENCY_CONTACT_ALT_NUMBER VARCHAR(15),
    STUDENT_EMERGENCY_CONTACT_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    STUDENT_EMERGENCY_OTHER_DETAILS TEXT,
    EMERGENCY_SHARES_STUDENT_ADDRESS BOOLEAN NOT NULL,

    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),

    CHECK (STUDENT_EMERGENCY_PHONE_COUNTRY_CODE SIMILAR TO PHONE_CODE_REGEX())
);

-- All valid
CREATE TABLE HEALTH_CONDITION (
    HEALTH_CONDITION_ID SERIAL PRIMARY KEY,
    HEALTH_CONDITION_NAME VARCHAR(30) UNIQUE NOT NULL,
    HEALTH_CONDITION_NOTES TEXT
);

-- All valid
CREATE TABLE STUDENT_HEALTH_CONDITION (
    STUDENT_ID INT NOT NULL,
    HEALTH_CONDITION_ID INT NOT NULL,
    SEVERITY SMALLINT NOT NULL, 
    STUDENT_HEALTH_NOTES TEXT,

    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (HEALTH_CONDITION_ID) REFERENCES HEALTH_CONDITION(HEALTH_CONDITION_ID),

    CHECK (SEVERITY BETWEEN 1 AND 5),

    PRIMARY KEY (STUDENT_ID, HEALTH_CONDITION_ID)
);

-- All valid
CREATE TABLE EVALUATION_SESSION (
    TUTOR_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    SESSION_DATETIME TIMESTAMP NOT NULL,
    ROOM_ID INT,
    SESSION_NOTES TEXT,
    IS_ONLINE BOOLEAN NOT NULL,

    FOREIGN KEY (TUTOR_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),

    PRIMARY KEY (TUTOR_ID, STUDENT_ID, SESSION_DATETIME)
);

-- All valid
CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID SERIAL PRIMARY KEY,
    STAFF_ID INT NOT NULL,
    SUBJECT_ID INT NOT NULL,
    SET_DATE TIMESTAMP NOT NULL,
    DUE_DATE TIMESTAMP,
    ASSIGNMENT_DESCRIPTION TEXT,

    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID),

    CHECK (DUE_DATE >= SET_DATE OR DUE_DATE IS NULL)
);

-- All valid
CREATE TABLE STUDENT_ASSIGNMENT (
    STUDENT_ID INT NOT NULL,
    ASSIGNMENT_ID INT NOT NULL,
    SUBMISSION_DATETIME TIMESTAMP NOT NULL,
    IS_ASSIGNMENT_ASSESSED BOOLEAN NOT NULL,
    ASSIGNMENT_PERCENTAGE DECIMAL(5, 2),
    ASSIGNMENT_WEIGHT DECIMAL(5, 2),

    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ASSIGNMENT_ID),

    CHECK (ASSIGNMENT_PERCENTAGE BETWEEN 0 AND 100 OR ASSIGNMENT_PERCENTAGE IS NULL),
    CHECK (ASSIGNMENT_WEIGHT BETWEEN 0 AND 100 OR ASSIGNMENT_WEIGHT IS NULL),

    PRIMARY KEY (STUDENT_ID, ASSIGNMENT_ID, SUBMISSION_DATETIME)
);

-- All valid
CREATE TABLE SESSION (
    SESSION_ID SERIAL PRIMARY KEY,
    SUBJECT_ID INT NOT NULL,
    ROOM_ID INT,
    SESSION_TYPE SESSION_TYPES NOT NULL,
    SESSION_STATUS VARCHAR(15) NOT NULL,
    SESSION_NAME VARCHAR(100) NOT NULL,
    SESSION_START TIMESTAMP NOT NULL,
    SESSION_END TIMESTAMP NOT NULL,
    IS_ONLINE BOOLEAN NOT NULL,

    FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),

    CHECK (SESSION_END >= SESSION_START)
);

-- All valid
CREATE TABLE SESSION_STUDENT (
    SESSION_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    ATTENDANCE_STATUS VARCHAR(15) NOT NULL,
    FEEDBACK_GENERAL_RATING SMALLINT,
    FEEDBACK_ONLINE_CONNECTION_QUALITY SMALLINT,
    FEEDBACK_CONCEPT_UNDERSTOOD_RATING SMALLINT,
    FEEDBACK_EXTRA_NOTES TEXT,

    FOREIGN KEY (SESSION_ID) REFERENCES SESSION(SESSION_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),

    CHECK (FEEDBACK_GENERAL_RATING BETWEEN 0 AND 10),
    CHECK (FEEDBACK_ONLINE_CONNECTION_QUALITY BETWEEN 0 AND 10),
    CHECK (FEEDBACK_CONCEPT_UNDERSTOOD_RATING BETWEEN 0 AND 10),

    PRIMARY KEY (SESSION_ID, STUDENT_ID)
);

-- All valid
CREATE TABLE SESSION_STAFF (
    SESSION_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,

    FOREIGN KEY (SESSION_ID) REFERENCES SESSION(SESSION_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    
    PRIMARY KEY (SESSION_ID, STAFF_ID)
);

-- All valid
CREATE TABLE ENROLMENT (
    ENROLMENT_ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    ENROLMENT_STATUS VARCHAR(15) NOT NULL,
    ENROLMENT_START_DATE DATE NOT NULL,
    ENROLMENT_END_DATE DATE NOT NULL,
    FINAL_GRADE_PERCENTAGE DECIMAL(5, 2),

    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),

    CHECK (ENROLMENT_END_DATE > ENROLMENT_START_DATE),
    CHECK (FINAL_GRADE_PERCENTAGE BETWEEN 0 AND 100 OR FINAL_GRADE_PERCENTAGE IS NULL)
);

-- All valid
CREATE TABLE STUDENT_PAYMENT (
    PAYMENT_ID SERIAL PRIMARY KEY,
    ENROLMENT_ID INT NOT NULL,
    PAYMENT_STATUS VARCHAR(15) NOT NULL,
    PAYMENT_AMOUNT DECIMAL(7,2) NOT NULL,
    PAYMENT_DATETIME TIMESTAMP NOT NULL,

    FOREIGN KEY (ENROLMENT_ID) REFERENCES ENROLMENT(ENROLMENT_ID),

    CHECK (PAYMENT_AMOUNT >= 0)
);