INSERT INTO branch(BRANCH_ID, BRANCH_NAME, BRANCH_ADDR1, BRANCH_ADDR2, BRANCH_CITY, BRANCH_POSTCODE, BRANCH_COUNTRY_CODE, BRANCH_EMAIL, BRANCH_PHONE_COUNTRY_CODE, BRANCH_PHONE_NUMBER)
VALUES
    (),
    (),
    (),
    (),
    (),
    (),
    (),
    (),
    (),
    ();